# Dependencies
markdown:         redcarpet
pygments:         true

# Analytics
analytics :
  tracking_id :   '暂无'
  site_name:      'txlong.github.io'

# Permalinks
permalink:        pretty

# Setup
excerpt_separator: <!--more-->

title:            '小龙'
tagline:          'Android开发相关博客'
description:      "记录开发生活中的点点滴滴"
url:              http://txlong.github.io

author:
  name:           '小龙'
  url:            https://txlong-onz.iteye.com

paginate:         5

# Custom vars
github:			https://github.com/txlong
weibo:   		http://weibo.com/u/2051318867